#!/bin/sh
#
#   verify SAML2 SP and IDP metadata
#   Author: Tom Morelly 
#   20201014

OPTIONS="--noout"

verify() {
    [ ! -f "$1" ] && echo "$1 is no a valid file. Exiting" && exit 1
    
    if XML_CATALOG_FILES=".xcatalog/saml-metadata.xml" xmllint --pretty 1 --schema saml-2.0-os/saml-schema-metadata-2.0.xsd "$2" "$1"; then
        exit 0
    else
        exit 1
    fi
}

usage() {
  printf "%s\n" "Usage: ${0##*/} [OPTIONS...]"
  printf "\n%s\n" "OPTIONS:"
  printf "  %-25s%s\n" "-f, --file" "path to metadata file"
  printf "  %-25s%s\n" "-v, --verbose" "verbose"
  exit 0 
}

main() {
    [ $# -eq 0 ] && usage 
    while [ $# -ge 1 ]; do
        case "${1}" in
            -f|--file)
            verify "$2" $OPTIONS
            exit 0
            ;;
            -v|--verbose)
            OPTIONS="--load-trace"
            ;;
            -h|--help)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
        ;;
        esac
        shift
    done
}


main "$@"
