#!/bin/sh
#
#   verify SAML2 SP and IDP metadata
#   Author: Tom Morelly 
#   20201014

# shellcheck disable=SC2002
OPTIONS="--noout"

verify() {
    # $1 path to file that is verified
    # $2 xmllint options

    # split metadata file in case it has multiple entityIDs
    tmp_dir=$(mktemp -d)
    csplit --prefix="$tmp_dir/metadata_" -sz "$1" '/<md:EntityDescriptor */' '{*}'

    for file in "$tmp_dir"/*; do
        entityID=$(cat "$file" | grep "entityID" | cut -d= -f2 | tr -d '"')
        echo "verifying metadata for entityID: $entityID"
        XML_CATALOG_FILES="xcatalog/saml-metadata.xml" xmllint --pretty 1 --schema saml-2.0-os/saml-schema-metadata-2.0.xsd "$2" "$file"
    done
         
    rm -rf "$tmp_dir"
}


usage() {
  printf "%s\n" "Usage: ${0##*/} [OPTIONS...]"
  printf "\n%s\n" "OPTIONS:"
  printf "  %-25s%s\n" "-f, --file" "path to metadata file"
  printf "  %-25s%s\n" "-v, --verbose" "verbose"
  exit 0 
}

main() {
    [ $# -eq 0 ] && usage 
    while [ $# -ge 1 ]; do
        case "${1}" in
            -f|--file)
            verify "$2" $OPTIONS
            exit 0
            ;;
            -v|--verbose)
            OPTIONS="--load-trace"
            ;;
            -h|--help)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
        ;;
        esac
        shift
    done
}


main "$@"
