name: build & test & release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install deps
      run: sudo apt-get install libxml2 libxml2-utils

    - name: build source
      run: sudo make
  test:
    steps: ubuntu-latest
    needs: [build]
    - name: run tests
      run: ./saml2-metadata-verifier -f test/valid-metadata.xml
