on: [push, pull_request]
name: CI
jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: build
          run: |
            sudo apt-get install -y libxml2-utils
            make
  
        - name: tests
          run: | 
            ./saml2-metadata-verifier.sh -f tests/valid_metadata.xml
            ./saml2-metadata-verifier.sh -f tests/invalid_metadata.xml || true


