name: pipeline

on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: sudo apt-get install libxml2 libxml2-utils
        
      - name: build src
        run: make

      - uses: FalcoSuessgott/rpm-tito-action@v1.0.6
