name: pipeline

on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FalcoSuessgott/rpm-tito-action@v1.2.4

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        id: rpm 

      - name: Upload rpms to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.rpm.outputs.rpm_path }}
          asset_name: saml2-metadata-verifier
          tag: ${{ github.ref }}
          overwrite: true
          body: "RPM releases by github actions"
