name: pipeline

on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FalcoSuessgott/rpm-tito-action@v1.0.6

      - uses: actions/upload-artifact@v2
        with:
          name: saml2-metadata-verifer.rpm
          path: /tmp/tito/noarch/*.rpm
