name: pipeline

on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FalcoSuessgott/rpm-tito-action@v1.2.2

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '/tmp/tito/noarch/*.rpm'
