name: pipeline

on: [push]

jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  build:
    name: build
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get install libxml2 libxml2-utils

      - name: build source
        run: make

  tests:
    name: tests
    needs: [build, linting]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get install libxml2 libxml2-utils

      - name: build source
        run: make

      - name: test should pass
        run: ./saml2-metadata-verifier -f test/valid-metadata.xml 
  
      - name: test should fail
        run: ./saml2-metadata-verifier -f test/invalid-metadata.xml || true
  
