name: Shell Scripts Unit Testing

on: [push]

jobs:
  build:
    runs-on: centos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install deps
      run: sudo yum install xmllib2-devel
      
    - name: build source
      run: sudo make

    - name: run tests
      run: ./saml2-metadata-verifier -f test/valid-metadata.xml
