name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install deps
      run: sudo apt-get install libxml2 libxml2-utils

    - name: build source
      run: sudo make

    - name: run tests
      run: ./saml2-metadata-verifier -f test/valid-metadata.xml 

    - name: run test
      run: ./saml2-metadata-verifier -f test/invalid-metadata.xml || true
